HTTP_PORT: 8888
db:
  driver: "postgresql"
  dsn: "postgres://postgres:123456@localhost:5432/demo?sslmode=disable&TimeZone=Asia/Shanghai"
  auto_migrate: true
  prefix:  ""
# redis 连接数据
rdb:
  addr: "localhost:6379"
  password: ""
  db: 2
  prefix: ""
# jwt
jwt:
  expire_time: 1440
  refresh_expire_time: 1440
  signing_method: "hs512"
  signing_key: "hellokey"
  refresh_signing_key: "hellokey"
logconf: # 日志配置
  isprod: false  # false,终端输出日志，true,输出到文件
# nacos
nacos:
  ip: "127.0.0.1"
  port: 8848
  client_name: "analyze-system.http"
  client_ip: 127.0.0.1
  client_port: 8888
  client_weight: 1